resolver: lts-21.21  # Or any recent LTS version you want to use
packages:
- .
extra-deps:
  - random-1.2.1.2   # Add the random library version you need
  - HUnit-1.6.2.0
  - monad-bayes-1.3.0.1
  - vty-unix-0.2.0.0
  - brick-2.3.2
  - vty-6.1
  - vty-crossplatform-0.4.0.0
  - free-5.2

